version: '3.8'
services:
  db:
    image: postgres:17.0-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: db
    ports:
      - 5432:5432
    networks:
      - postgres

networks:
  postgres:
    driver: bridge