= Quarkus-Anwendung mit PostgreSQL und Dev Services
:author: Balint Balazs
:revnumber: 1.1
:revdate: 2024-01-11
:doctype: book
:reproducible:
:icons: font
:sectnums:
:toc:
:source-highlighter: rouge
:docinfo: shared

== Voraussetzungen

Bevor Sie beginnen, stellen Sie sicher, dass die folgenden Tools installiert sind:

*   **Java 17** oder höher (z.B. von https://adoptium.net/[https://adoptium.net/])
*   **Maven** 3.8.1 oder höher (https://maven.apache.org/download.cgi[https://maven.apache.org/download.cgi])
*   **Docker** (für die Ausführung von Dev Services) (https://docs.docker.com/get-docker/[https://docs.docker.com/get-docker/])
*   **Ein Terminal** oder eine **Eingabeaufforderung**
*   **Ein Code-Editor** oder eine **IDE** (z.B. IntelliJ IDEA, VS Code, Eclipse)

Hinweis: PostgreSQL muss nicht manuell installiert werden, da Quarkus Dev Services dies automatisch für Sie übernimmt.

== Projekt erstellen

Erstellen Sie ein neues Quarkus-Projekt mit den notwendigen Erweiterungen, indem Sie den folgenden Befehl in Ihrem Terminal ausführen:

[source,bash]
----
mvn io.quarkus.platform:quarkus-maven-plugin:3.6.4:create \
    -DprojectGroupId=com.example \
    -DprojectArtifactId=quarkus-postgres-app \
    -DclassName="com.example.resource.PersonResource" \
    -Dextensions="resteasy-jackson,hibernate-orm-panache,jdbc-postgresql"
cd quarkus-postgres-app
----

Dieser Befehl erstellt ein neues Quarkus-Projekt mit:

*   `resteasy-jackson`: Für die Serialisierung und Deserialisierung von JSON in den REST-Endpunkten.
*   `hibernate-orm-panache`: Für die Datenbankinteraktion mit Panache.
*   `jdbc-postgresql`: Für die Verbindung zur PostgreSQL-Datenbank.

== Abhängigkeiten

Die benötigten Abhängigkeiten wurden durch den vorherigen Befehl bereits zur `pom.xml` hinzugefügt. Hier ist ein Ausschnitt aus der generierten `pom.xml`:

[source,xml]
----
<dependencies>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-resteasy-jackson</artifactId>
    </dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-hibernate-orm-panache</artifactId>
    </dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-jdbc-postgresql</artifactId>
    </dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-junit5</artifactId>
        <scope>test</scope>
    </dependency>
    <dependency>
        <groupId>io.rest-assured</groupId>
        <artifactId>rest-assured</artifactId>
        <scope>test</scope>
    </dependency>
</dependencies>
----

== Konfiguration der PostgreSQL-Datenbank

Quarkus Dev Services startet automatisch eine PostgreSQL-Datenbank in einem Docker-Container für Sie, wenn diese im Dev- oder Testmodus läuft und konfiguriert ist. Sie müssen jedoch die Verbindungsdetails in der Konfiguration festlegen. Öffnen Sie die Datei `src/main/resources/application.properties` und fügen Sie die folgenden Konfigurationen hinzu:

[source,properties]
----
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus
quarkus.datasource.devservices.image-name=postgres:15-alpine
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.format-sql=false
----

**Erläuterungen:**

*   `quarkus.datasource.db-kind=postgresql`: Gibt an, dass PostgreSQL als Datenbank verwendet wird.
*   `quarkus.datasource.username`: Der Benutzername für den Datenbankzugriff (Standard: `quarkus`).
*   `quarkus.datasource.password`: Das Passwort für den Datenbankzugriff (Standard: `quarkus`).
*   `quarkus.datasource.devservices.image-name`: Gibt das zu verwendende Docker-Image für die PostgreSQL-Datenbank an (hier: `postgres:15-alpine`, eine schlanke PostgreSQL-Version).
*   `quarkus.hibernate-orm.database.generation=drop-and-create`: Konfiguriert Hibernate ORM so, dass die Datenbanktabellen bei jedem Start der Anwendung gelöscht und neu erstellt werden. Dies ist **nur für die Entwicklung** geeignet. In der Produktion sollten Sie `update` oder `validate` verwenden.
*   `quarkus.hibernate-orm.log.sql=true`: Aktiviert das Logging der SQL-Anweisungen, was bei der Fehlersuche hilfreich sein kann.
*   `quarkus.hibernate-orm.log.format-sql=false`: Deaktiviert die Formatierung der SQL-Anweisungen im Log.

**Wichtiger Hinweis:**

Dev Services ist standardmäßig aktiviert, wenn die Anwendung im Entwicklungsmodus (`mvn quarkus:dev`) oder Testmodus ausgeführt wird. Für den Produktivmodus müssen Sie eine PostgreSQL-Datenbank manuell bereitstellen und die entsprechenden Konfigurationsparameter (z.B. `quarkus.datasource.jdbc.url`) setzen.

== Erstellen der `Person`-Entität

Erstellen Sie eine Entität, die Sie in der Datenbank speichern möchten. Erstellen Sie die Datei `src/main/java/com/example/model/Person.java` mit folgendem Inhalt:

```java
package com.example.model;

import io.quarkus.hibernate.orm.panache.PanacheEntity;

import javax.persistence.Entity;

@Entity
public class Person extends PanacheEntity {
    public String firstName;
    public String lastName;
    public String email;

    public Person() {
    }

    public Person(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }
}