name: Run all test in  devservices-demo project

on:
  push:
    paths:
      - 'devservices-demo/**'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'devservices-demo/pom.xml'

      - name: Set execute permission for the test script
        run: chmod +x .github/cicd/devservices-demo-scripts/run-main-test-devservices.sh

      - name: Execute test script
        run: .github/cicd/devservices-demo-scripts/run-main-test-devservices.sh