name: Test continuous-testing-demo

on:
  push:
    paths:
      - 'continuous-testing-demo/**'
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-backend:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
          cache-dependency-path: 'continuous-testing-demo/pom.xml'

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add remote host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Create SSH Tunnel
        run: |
          ssh -f -N -L 5432:localhost:5432 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -o StrictHostKeyChecking=no
          sleep 3 # Give the tunnel some time to establish (adjust if necessary)

      - name: Set execute permission for the test script
        run: chmod +x .github/cicd/execute-test.sh

      - name: Execute test script
        run: ./.github/cicd/execute-test.sh